### ISSUE TITLE
DTC command line doesn't work with 1.3 or 1.4

### ISSUE THREAD

**Issue by faceless2** [nomel/beaglebone#1]
On a newly installed Ubuntu 13.04 on BeagleboneBlack, I'm unable to run the "compile.sh" script. The issue is the "dtc" command arguments, which look like

dtc -O dtb -o gpio-P9.42b-00A0.dtbo -b 0 -@ -I dts gpio-P9.42b-00A0.dts

But "-@" is not a valid argument for "dtc" 1.3 or 1.4. If I remove it, I get

Error: gpio-P9.42b-00A0.dts:5.2-8 syntax error
FATAL ERROR: Unable to parse input tree

I have tested with both the "dtc" from the device-tree-compiler package in Ubuntu 13.04, and a newly compiled 1.4.0 build from git sources at http://git.jdl.com/gitweb/?p=dtc.git;a=summary

I can install your prebuilt binaries, of course, but it would be nice to build them from source.

**Comment by SaintGimp** [comment]
The version of dtc on Ubuntu needs to be patched in order to work with the BBB.  See [instructions here](http://eewiki.net/display/linuxonarm/BeagleBone#BeagleBone-Upgradedistro%22device-tree-compiler%22package) for a script that will apply the patch for you, then the dtc executable will have the -@ switch and everything will work.  The BBB Angstrom image has the patched dtc built-in but Ubuntu does not.  I don't think there's any way around that except that maybe compile.sh could include a friendly message about what needs to be done.

**Comment by faceless2** [comment]
Thanks, that was all I needed, it now works fine.
